apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-volume-2
  namespace: logging
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-prod1.biplus.com.vn
          - k8s-prod2.biplus.com.vn
          - k8s-prod3.biplus.com.vn